#!/usr/bin/env nix-shell
#! nix-shell -i nu --pure -p nushell nix cacert

# Regenerate ./sources.nix from the Waydroid OTA channels.
# Modeled after the nixpkgs `qq` package's update.sh.
# Run from this directory (`updateScript` invokes it in place).

const system_ota = "https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json"
const vendor_ota = "https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json"

# Newest build (OTA lists are ordered oldest-first).
def latest [ota: string]: nothing -> record {
  http get $ota | get response | sort-by datetime | last
}

# sri256 hash of a URL, downloading through the Nix store cache.
def prefetch-sri [url: string, name: string]: nothing -> string {
  nix --extra-experimental-features nix-command store prefetch-file --json --name $name $url
  | from json
  | get hash
}

# SourceForge's `/projects/<p>/files/.../download` URLs answer with an HTML
# interstitial; rewrite them to the direct mirror URLs that serve the file.
def direct [url: string]: nothing -> string {
  $url
  | str replace "https://sourceforge.net/projects/" "https://downloads.sourceforge.net/project/"
  | str replace "/files/" "/"
  | str replace --regex "/download$" ""
}

cd ($env.CURRENT_FILE | path dirname)

let system = latest $system_ota
let vendor = latest $vendor_ota
let parsed = $system.filename | parse --regex '^lineage-(?<ver>[0-9.]+)-(?<date>[0-9]{8})-'
let version = $"($parsed.0.ver)-($parsed.0.date)"

let generated = $'# Generated by ./update.nu - do not update manually!
# Last updated: (date now | format date "%Y-%m-%d")
{ fetchurl }:
{
  version = "($version)";
  system = fetchurl {
    url = "(direct $system.url)";
    hash = "(prefetch-sri (direct $system.url) $system.filename)";
  };
  vendor = fetchurl {
    url = "(direct $vendor.url)";
    hash = "(prefetch-sri (direct $vendor.url) $vendor.filename)";
  };
}
'

$generated | save --force "sources.nix"
print $"updated to ($version)"
