ai:
    accessTokens:
        deepseek: ENC[AES256_GCM,data:FM0T5S1eLzoze0AYPvh9TprStZZB/7RbySr4fonRYvLw6f0=,iv:bJMQpvvL45bdkko8jTd2UZVluDCBrDZH4T9ushuIr8o=,tag:BgLihBmduxjqki8ZL+Vrcw==,type:str]
        kimi: ENC[AES256_GCM,data:Wo3PgcbgtMn1Xvp6Z1+Rk9oyz99lPSn1GwP5Lq5uT5vHMXxpYVu8V9ybn+akgY/Fue6PrJ43WDRT3VEhAb+UU3nXdt4YaQ5B,iv:EiykEmCFPxc4WPL4CBFW4LruxFN0BSqm+HXga/UNJr0=,tag:BFQIyHdaC8yTnQ45EhDWxg==,type:str]
        mimo: ENC[AES256_GCM,data:EDdtNOY9LDyhQQKVAr3eNrJsxjnY0fewba+tHji6SAvHQdPJbHWL2SHQHpLZFt5ntLU7,iv:JstU6Hxg4yKCLEcwmrvXGnCiW5w1S4X7LjVZvWxbMgk=,tag:PdvLJM4l77SHyRq3b0AZVw==,type:str]
mihoyo:
    providerUrls:
        alink: ENC[AES256_GCM,data:q3nrmR7jsKNPoP6VyGLofipBPzX/Niu7mQgS17y9R30OjxyRvnQnLFsG00RZddNzU3ANsZbkRRzSPnOvWVGrLy9kROkuscu90+5mee/lFIQFHd9inNb5YEP0ilQ=,iv:qgh/hLISUPwJ3N6SAfRokgX54quULaHQ8zUFXtBvhDY=,tag:NNuwaMTCsr9Q+Q72v6TIiQ==,type:str]
smartd:
    bot:
        target: ENC[AES256_GCM,data:VEKTksI/EDzakQ==,iv:ADMA6VNT+c2c8C099//HxGa9GEXXMots9LpzGOrV/ic=,tag:4fru2/0O6oYqNi7C0HeRYw==,type:str]
        token: ENC[AES256_GCM,data:ZuiOTJ1cyEc3YXHnFJo7jNE4A1qBi/W8KUG2moOR1FBmez0pR6Pn09P2DwdRyw==,iv:C3YJ0ZrbU7Ziz4rhLHN5P7RDHdCrdT8qc4gzyj48UtI=,tag:b/8DAzu/KjZ/yUCqlV7bCw==,type:str]
tlsCert:
    keys:
        lialh4.cyou.pem.key: ENC[AES256_GCM,data:1Wx8/qWbRUAnMlMKIMV6d9YPrL9MPcIxwpH3uTA0WHJAUB31fJBuXfaabjIPuNcdIZNyw9SgsQGYBVyFlxpMSp2SNsSynmthgMI36mvtfFhfJ3nRDUxZtsKIpJ1jJQ0JdPKhkz9Umzr0ekxKQbMQhMB7ZlahwiBM2v1g7OZXcGzQniv6UQeZoS1BMO7/d3TMdChXBvcKXEMMMaRDstzwUWiVUXtqDIzBmOkbicGF3ROQbPxeUlsSWs1bsQmDvGfLZ8y/bPVMJ34ahnFva3zecfpGIPlOoAUg6YIQkBekc5Uw8RiZgtICA81WaKNbhhucfg==,iv:SUIZaAoh9bLMiEMgAOSkR5PDfihyVQad7cUgJXzT/dg=,tag:6lS6KQfTNT8OjM/0K5BmMg==,type:str]
vaultwarden:
    adminToken: ENC[AES256_GCM,data:My3d4/uhkyYNXo1ozTKdPzSmV1DSk2sxhlQF23VhdyMZSpZi6hTlVW2DLj+z8cqUkQ32yW8x4Ten8vAwqskt+pHDN59nm2O3Kt2gWT3xWcrOPZzg6x1qwW0zW87oPJ2YfYZFuv4j57psiENGQp3P06AtUyvW4A==,iv:KlZXRpxd4qH6H6jIJAAUhg+EHZVV4nJpu/XZckoUako=,tag:o2CqdBFzQNgl3s9Ddi4TjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTUx0SlVUOVI0ZlpYcnc4
            WUdrM0ZPa2lsS1JCcTcyQkk4ci9FZlRENWd3CmZncG11T25rN3NKZHNZY2tCV0h5
            c0VuN1ZxVU5UcExCditvcDZrUTViTDgKLS0tIFhoMU9TQks2MUFSYzBsNjl3eHJM
            TVVJNkdMaVZmVDNPUE1YVmh2UHN1dXMKfwhXEIs/8DQfhZcfP6uynUOKIEuusyLT
            1mTZwolknZKv+be98P7fG293mQ+avG0Cl7CKYo4NgMEwDF0NQDY1iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13h6k5sxuzcw6wrc6wj804f24mzq9qu03swhu555zuz7vqeweuswsceq8qs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VkM3SjFCZlRuMkNOZ3U1
            VHp1eXBESENhbU5DWTdSZFhtVG52Z2NNclRvCmxxUFZabWIrcWVQRU1SOVc2bjd5
            U0JlTC9Tb3R3WGJqOXZLamlGTmdGRjgKLS0tIHE2ZDd0QzdnNlExM1cvckhHSjVP
            azdBbjFxaGFVVThDelhPUTRYT2VCZmsKmhNMLx2JjI8eW/l49h+qBGeEGRPp0Ss3
            M+MaMQqS2iSKP8pm1cM1IN1Ha470nfesSIA7KHzotRRX+wFPmlqwKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uy3zxre0xvmuhfgmxyvq6wccxjnd6qq33efg0dd5s2ym4yz2wugstr8mz0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQjQvMnBkb2JvTzQ3eHM5
            bVgrU0pZa1RodXZJbG1wT3Vrb0hGRlc0S2p3Cm9YYi9vZWRZSkZWR2tiYUUraWl1
            c0FSUlh1N3dkblBLYXRNZklUVXgrU1EKLS0tIHNHNWZJZjNxeTdSOGNsRys4cms4
            TXNobmVISktmUklsVTZvNmRmYUVzaGsKGYdn0cpGwkMPWncReZT61XEeuHYn5d7T
            7Y2sjcYvyHC6esDYSsXqIuumxSQjtHAs87wjZxkcanlHxprTxl80fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xsh3h76kgprlway8ysuzxq2pqnp0ppujq9tlsrggt3df4y5qgycqlqtl48
    lastmodified: "2026-09-11T02:12:44Z"
    mac: ENC[AES256_GCM,data:2eyVvMpBtKgB76cJ1HDC5VCRmwPW4YmJJuJEeIpLO+dZWopOETnUqiw6jW3t6PhXAk5IYfHI8YHdmXinGPrkWPp+yZr8hugq6KPzlcwYWPBqEowrpUHHz6gkUmQkrgbxMfGaOC0t8Xi4DZkoBhv2/UuJ3Tgsvmt9Pj7solg9SKc=,iv:2wIHcQi0nXopds0M26ogjxi8MwYAMBpDNUtFIG2EjsM=,tag:IglwSLoT1KiFsuiHLEKbtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
