ai:
    accessTokens:
        deepseek: ENC[AES256_GCM,data:FM0T5S1eLzoze0AYPvh9TprStZZB/7RbySr4fonRYvLw6f0=,iv:bJMQpvvL45bdkko8jTd2UZVluDCBrDZH4T9ushuIr8o=,tag:BgLihBmduxjqki8ZL+Vrcw==,type:str]
        kimi: ENC[AES256_GCM,data:Wo3PgcbgtMn1Xvp6Z1+Rk9oyz99lPSn1GwP5Lq5uT5vHMXxpYVu8V9ybn+akgY/Fue6PrJ43WDRT3VEhAb+UU3nXdt4YaQ5B,iv:EiykEmCFPxc4WPL4CBFW4LruxFN0BSqm+HXga/UNJr0=,tag:BFQIyHdaC8yTnQ45EhDWxg==,type:str]
        mimo: ENC[AES256_GCM,data:EDdtNOY9LDyhQQKVAr3eNrJsxjnY0fewba+tHji6SAvHQdPJbHWL2SHQHpLZFt5ntLU7,iv:JstU6Hxg4yKCLEcwmrvXGnCiW5w1S4X7LjVZvWxbMgk=,tag:PdvLJM4l77SHyRq3b0AZVw==,type:str]
mihoyo:
    providerUrls:
        alink: ENC[AES256_GCM,data:q3nrmR7jsKNPoP6VyGLofipBPzX/Niu7mQgS17y9R30OjxyRvnQnLFsG00RZddNzU3ANsZbkRRzSPnOvWVGrLy9kROkuscu90+5mee/lFIQFHd9inNb5YEP0ilQ=,iv:qgh/hLISUPwJ3N6SAfRokgX54quULaHQ8zUFXtBvhDY=,tag:NNuwaMTCsr9Q+Q72v6TIiQ==,type:str]
smartd:
    bot:
        target: ENC[AES256_GCM,data:VEKTksI/EDzakQ==,iv:ADMA6VNT+c2c8C099//HxGa9GEXXMots9LpzGOrV/ic=,tag:4fru2/0O6oYqNi7C0HeRYw==,type:str]
        token: ENC[AES256_GCM,data:ZuiOTJ1cyEc3YXHnFJo7jNE4A1qBi/W8KUG2moOR1FBmez0pR6Pn09P2DwdRyw==,iv:C3YJ0ZrbU7Ziz4rhLHN5P7RDHdCrdT8qc4gzyj48UtI=,tag:b/8DAzu/KjZ/yUCqlV7bCw==,type:str]
tlsCert:
    keys:
        lialh4.cyou.pem.key: ENC[AES256_GCM,data:1Wx8/qWbRUAnMlMKIMV6d9YPrL9MPcIxwpH3uTA0WHJAUB31fJBuXfaabjIPuNcdIZNyw9SgsQGYBVyFlxpMSp2SNsSynmthgMI36mvtfFhfJ3nRDUxZtsKIpJ1jJQ0JdPKhkz9Umzr0ekxKQbMQhMB7ZlahwiBM2v1g7OZXcGzQniv6UQeZoS1BMO7/d3TMdChXBvcKXEMMMaRDstzwUWiVUXtqDIzBmOkbicGF3ROQbPxeUlsSWs1bsQmDvGfLZ8y/bPVMJ34ahnFva3zecfpGIPlOoAUg6YIQkBekc5Uw8RiZgtICA81WaKNbhhucfg==,iv:SUIZaAoh9bLMiEMgAOSkR5PDfihyVQad7cUgJXzT/dg=,tag:6lS6KQfTNT8OjM/0K5BmMg==,type:str]
vaultwarden:
    adminToken: ENC[AES256_GCM,data:My3d4/uhkyYNXo1ozTKdPzSmV1DSk2sxhlQF23VhdyMZSpZi6hTlVW2DLj+z8cqUkQ32yW8x4Ten8vAwqskt+pHDN59nm2O3Kt2gWT3xWcrOPZzg6x1qwW0zW87oPJ2YfYZFuv4j57psiENGQp3P06AtUyvW4A==,iv:KlZXRpxd4qH6H6jIJAAUhg+EHZVV4nJpu/XZckoUako=,tag:o2CqdBFzQNgl3s9Ddi4TjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb3ZqYWtkRkIzbmNjZVBM
            Zmt1eEN5cFV4MlM4WDJoRFN3dzMzU21RbzFBCnRyRWI1UVpSbzY0b1hrbGs2TVc2
            aFR5WDRXTmNXcEh3L09ON1NuZTZlMjAKLS0tIC9XUkI3cGlRSWZ2TmJQVmlCdWV0
            dWltRVFuOWxlRFUrV1VoalVVODJPVmMKHe6aXsrmkAkPxrJoEpxsxsAnAbyazuHz
            HacqLq6YjyLZd86k6remAwzuzzgLfsu6xav52dl8vDzH3Jla5teVuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13h6k5sxuzcw6wrc6wj804f24mzq9qu03swhu555zuz7vqeweuswsceq8qs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveFUwNGVpTllDbFZJcGQ0
            cFVhNEFLOHE0VkFieFRxUEV4NVFJbisvTGdvCmtwM1FIeUJiMURaQzl2bTg1ZzFI
            dkZmcmFpMlB4UVpEYlVsWEhla2YvUzAKLS0tIGw5U3NrdE9vNFMxQ2RrU2JrVnV3
            TFdjL3BXZGo0RUFGSkdRRTh3bERYMTgKtM/HJ8lzRX6Gmlmq70EKHwbFM/r2t7X0
            WcGqS6Brz9X7Z3EIXSMTS0COe8qJonFMKYYKCNRAYmVj2h3HosMH/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uy3zxre0xvmuhfgmxyvq6wccxjnd6qq33efg0dd5s2ym4yz2wugstr8mz0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbkg0eU1QdmNhTGxVMnh1
            YnlMTkw1MFZiUFdML01ocXJIZFUydUZsSGc4CkZ4SjJhbTVGa3BRYkNTSHNOQVVm
            eEdGQ2FrRFJOY2tORVBFeWFSTjRWU28KLS0tIGVBdWYxQ1h5dzMzV1JFb2FZTXRJ
            TWhRRitxSEFaeHpmNWpyS2czVjZyUzAKYUXuFxzffgA+ywfyD1qUlsVc0q4BSEhC
            JedP+uhXJN26pJiVuOGfCoqau2iTQZZxfByePWNyaik14bUQQdUJgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xsh3h76kgprlway8ysuzxq2pqnp0ppujq9tlsrggt3df4y5qgycqlqtl48
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWFYrNyt3ZGk3YTBWQlh1
            ckJnZmRvbUd5YzVXWm04RS9EbHlaQzloSkhBCnFGaWs5OHY0L2NYd1pqUnBvcEgv
            d0x1eVNuT056SjRXdXJUMThHNmRuRlEKLS0tIHdxQ2pBdnBQVE5oUHRsbm0rQ2dr
            THMwZVQwOHNpVTFrNU1hb1ltSWdOSjQKJRVrB5Ej6tGdD5T9NM8ZJINnkYtn/Bx2
            Jlhoj07sVrs+KNcF+X1VC3EEXQsbv9Mf5xOCfvVR/OFDXzG/Pc8dig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zh97yzwr3jchnkfemg0een57hfaexulxptgwfqhejsds48r593qsku75py
    lastmodified: "2026-09-11T02:12:44Z"
    mac: ENC[AES256_GCM,data:2eyVvMpBtKgB76cJ1HDC5VCRmwPW4YmJJuJEeIpLO+dZWopOETnUqiw6jW3t6PhXAk5IYfHI8YHdmXinGPrkWPp+yZr8hugq6KPzlcwYWPBqEowrpUHHz6gkUmQkrgbxMfGaOC0t8Xi4DZkoBhv2/UuJ3Tgsvmt9Pj7solg9SKc=,iv:2wIHcQi0nXopds0M26ogjxi8MwYAMBpDNUtFIG2EjsM=,tag:IglwSLoT1KiFsuiHLEKbtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
